TRAIN:
  ENABLE: False
  DATASET: cataract-101
  BATCH_SIZE: 64
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: "/home/majeedi/cataract/slowfast/pretrained/I3D_8x8_R50.pkl"
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8 # we have downsampled the framerate by half
  TRAIN_JITTER_SCALES: [256, 320]
  INPUT_CHANNEL_NUM: [3]
  READ_VID_FILE: True
  STRIDE: 16
  PATH_TO_DATA_DIR: "/home/majeedi/cataract/cataract-101/videos"
  PATH_PREFIX: ""
  VID_LIST: "/home/majeedi/cataract/cataract-101/videos/vid_list.csv"
  TMP_FOLDER: "./tmp"
  FPS: 25
  VID_FILE_EXT: ".mp4"
  SAMPLE_SIZE: [400, 300]
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 400
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: cataract-101
  BATCH_SIZE: 16
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

LOG_MODEL_INFO: False
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: "./resnet_feats"
